#pragma config(Motor,  port2,           left,          tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           right,         tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           army,          tmotorVex393_HBridge, openLoop, encoderPort, None)
#pragma config(Motor,  port5,           clawy,         tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while (1==1)
{
motor[left] = vexRT[Ch2];
motor[right] = vexRT[Ch3];


if (vexRT[Btn5U]==1){
  motor[army] = 127;
}
else if(vexRT[Btn5D]==1){
	motor[army] = -127;
}
else if(vexRT[Btn5D]==0){
	motor[army]=0;
}

if (vexRT[Btn6U]==1){
motor[clawy] = 127;
}
else if (vexRT[Btn6D]==1){
  motor[clawy] = -127;
}
else if (vexRT[Btn6D]==0){
  motor[clawy] = 0;
}
}
}
